### ISSUE TITLE
Update fails on 2015/01/27 when cropping

### ISSUE THREAD

**Issue by lawinslow** [USGS-CIDA/CIDA-Viz#352]
Fails at this line. Not sure why. 
https://github.com/USGS-CIDA/CIDA-Viz/blob/master/ca_drought/R/drought_map.R#L29

**Comment by jiwalker-usgs** [comment]
my guess is they changed the format of the download in some way that the path to the data has changed

**Comment by lawinslow** [comment]
I checked a bunch of this. The file downloads fine. It unpacks and reads into R fine. But when the crop is applied, it fails. I thought I knew what the issue was at first, but now I don't know what's up or down.

**Comment by lawinslow** [comment]
Seems to be an input data issue. QuantumGIS and gdal says the drought layer shapefile has issues. Used a separate tool to crop it and everything seems to be working. Hopefully, this week's output won't have the same polygon issue.

**Comment by lawinslow** [comment]
ugh, that just borks the geojson that comes out. My vote is to see what happens with this week's drought layer. If it works well, we just skip Jan 27.

**Comment by jread-usgs** [comment]
agreed.

**Comment by eread-usgs** [comment]
Still getting this error:

OGR data source with driver: ESRI Shapefile 
Source: "../shp", layer: "USDM_20150127"
with 5 features and 4 fields
Feature type: wkbMultiPolygon with 2 dimensions
 Show Traceback
 
 Rerun with Debug
 Error in RGEOSBinTopoFunc(spgeom1, spgeom2, byid, id, drop_not_poly, "rgeos_intersection") : 
  TopologyException: Input geom 0 is invalid: Self-intersection at or near point -87.738320058939252 30.296150036099366 at -87.738320058939252 30.296150036099366

**Comment by jread-usgs** [comment]
bummer. bad shapefile...

**Comment by jread-usgs** [comment]
http://gis.stackexchange.com/questions/119474/clipping-two-spatialpolygons-error-in-rgeosbintopofunc

**Comment by jread-usgs** [comment]
looking into this now

**Comment by jread-usgs** [comment]
got it. 
```R
unpack_clip_save_geojson = function(date){
	fmt_date = format(date, '%Y%m%d')
	zipfile = sprintf('../shp/USDM_%s_M.zip', fmt_date)
	unzip(zipfile, exdir='../shp')
	
	data = readOGR('../shp', paste0('USDM_', fmt_date))
	clipped.data = crop(data, ca_outline, byid=TRUE)
	clipped.simp = gSimplify(clipped.data, tol = .03, topologyPreserve=TRUE)
	to.save = SpatialPolygonsDataFrame(clipped.simp, clipped.data@data)
	
	writeOGR(to.save, 'tmp', layer="sp", driver="GeoJSON")
	to_rename = '../../Vizzies/public_html/data/drought_shp/USDM_%s.json'
	fname = sprintf(to_rename, fmt_date)
	
	file.rename('tmp', fname)
	
}
```
to
```R
unpack_clip_save_geojson = function(date){
	fmt_date = format(date, '%Y%m%d')
	zipfile = sprintf('../shp/USDM_%s_M.zip', fmt_date)
	unzip(zipfile, exdir='../shp')
	
	data = readOGR('../shp', paste0('USDM_', fmt_date))
  data_0buff <- gBuffer(data, byid=TRUE, width=0)
	clipped.data = crop(data_0buff, ca_outline, byid=TRUE)
	clipped.simp = gSimplify(clipped.data, tol = .03, topologyPreserve=TRUE)
	to.save = SpatialPolygonsDataFrame(clipped.simp, clipped.data@data)
	
	writeOGR(to.save, 'tmp', layer="sp", driver="GeoJSON")
	to_rename = '../../Vizzies/public_html/data/drought_shp/USDM_%s.json'
	fname = sprintf(to_rename, fmt_date)
	
	file.rename('tmp', fname)
	
}
```

**Comment by jread-usgs** [comment]
running it now

**Comment by jread-usgs** [comment]
resolved.
