### ISSUE TITLE
Snow Data

### ISSUE THREAD

**Issue by lfarrell** [USGS-CIDA/CIDA-Viz#358]
Not an issue, but a question. I was wondering what you all did with snow dates that appear to be in the future. Such as the Dec. 2015 readings for Dan Valley in New Mexico. http://www.wcc.nrcs.usda.gov/nwcc/rgrpt?station=08P05&report=snowmonth_hist. I'm trying to incorporate snow levels into my own viz on western water, and it's unclear what to do with years that start with a Dec reading. Is it from the year before or the current year?

Thanks,
Dean

**Comment by lawinslow** [comment]
Hi Dean, I'm pretty sure all that data is reported by [water year](http://en.wikipedia.org/wiki/Water_year). So October to December of 2014 is considered part of "water year" 2015 and gets labeled as such. I'll let my colleagues chime in if I've improperly characterized anything.

-Luke

**Comment by lfarrell** [comment]
Ah, thanks. Hadn't considered that.  Sorry to hijack your issues list.  I really like the viz.

Dean

**Comment by jread-usgs** [comment]
Thanks for the compliment Dean!
