### ISSUE TITLE
Y Axis Labels on Reservoir Chart Wrong

### ISSUE THREAD

**Issue by cschroed-usgs** [USGS-CIDA/CIDA-Viz#359]
![messed up axis labels](https://cloud.githubusercontent.com/assets/2349007/4704901/27554782-5876-11e4-8bd7-02cea392b375.png)

**Comment by cschroed-usgs** [comment]
Spacing is wrong. "75" is missing.

**Comment by cschroed-usgs** [comment]
Looks like the spec for the issue omitted the "75":
https://github.com/USGS-CIDA/CIDA-Viz/issues/188

**Comment by jread-usgs** [comment]
Whoops. @mwernimont can you fix? good eyes @cschroed-usgs
