### ISSUE TITLE
only one stream data point for 20160531

### ISSUE THREAD

**Issue by eread-usgs** [USGS-CIDA/CIDA-Viz#436]
Didnt see any errors when I ran the code... but I'm on a bad internet connection, not sure if that may have impacted it. @jread-usgs 
![screen shot 2016-06-03 at 5 54 06 am](https://cloud.githubusercontent.com/assets/7794368/15775386/aa0fdac4-294f-11e6-8d01-7a05a390ae33.png)

**Comment by jread-usgs** [comment]
That's no good. I will take a look.

**Comment by jread-usgs** [comment]
must have been fluke?
![image](https://cloud.githubusercontent.com/assets/2349007/15780733/aec45702-2968-11e6-9f68-84e43f725df2.png)

PR coming
